stages:
  - install
  - build

variables:
  NODE_ENV: production
  NODE_VERSION: "14.21.3"

image: node:${NODE_VERSION}

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g npm@7
  - npm ci

install_dependencies:
  stage: install
  script:
    - echo "Dependencies installed"

build_app:
  stage: build
  script:
    - npm run build -- --configuration production
  artifacts:
    paths:
      - dist/
